### ISSUE TITLE
NVE Repl Link 404s

### ISSUE THREAD

**Issue by scottwarren** [ehmicky/nve#1]
The [repl.it link](https://repl.it/@ehmicky/nve) in the readme 404s for me, maybe the 'snippet' is private?

![image](https://user-images.githubusercontent.com/2718494/62690831-1f40ef80-b9d6-11e9-89de-b515fe5f2d23.png)

PS: nice project!

**Comment by scottwarren** [comment]
Your [repl.it user page](https://repl.it/@ehmicky) lists the following repls:

![image](https://user-images.githubusercontent.com/2718494/62691009-70e97a00-b9d6-11e9-8275-b232286ff1af.png)

I thought maybe the link could have been wrong, but just looks like a permissions issue?

**Comment by ehmicky** [comment]
Hi Scott, nice you enjoy this project!

I just started this project yesterday, so the examples and `repl.it` are still missing. I also need to add some unit tests, finish the documentation and create a logo. I should hopefully be done today with all this. I will post on this issue once I'm done, cheers!

**Comment by scottwarren** [comment]
Oh, my bad! No worries! I saw that you created the project and checked it out. Thanks for the quick response 🙏🏼

**Comment by ehmicky** [comment]
The project is now all tested and I finished the documentation and examples. I also split it up in 6 different small modules in case anyone needs the use the inner logic. 

I've added some benchmarks (10 times faster than `nvm run`). Hope you enjoy!

**Comment by scottwarren** [comment]
Thanks! Again my apologies for jumping the gun on creating the issue

**Comment by ehmicky** [comment]
No worries, I'm glad you're checking out my new repos :)

@all-contributors please add @scottwarren for his question on repl.it since I might have forgotten otherwise.
