### ISSUE TITLE
Question about releases like 4.0.1

### ISSUE THREAD

**Issue by papb** [ehmicky/nve#10]
Hello :grimacing: sorry for not following the issue template; this is just a question. I watch this repository and noticed that there are a few releases (bumping the patch version) to which your release notes is simply 'internal changes'. What is the point of these releases? (This is not criticism, just a question). When such a release is made, why should a consumer update? How to decide between updating / not updating? From a consumer point of view, nothing changed, right? Thanks for the attention :)

**Comment by ehmicky** [comment]
Hi @papb, good feedback! And thanks for watching out this repository changelog :)

I try to keep only user-facing features in the changelog. `4.0.1` release is modifying some internal API that is undocumented.

However based on your feedback I think I should either: 
  - not make a release then
  - if the release only contains internal changes, explain them even if they do not impact usage

What do you think?

**Comment by papb** [comment]
Hmm... My main confusion can basically be reworded as: why make a release that doesn't change anything? (from the point of view of a consumer)

GitHub has a very nice feature of 'watching releases' of repositories. I have this turned on on a lot of repositories. I think watchers would be confused by looking at a release that basically doesn't change anything. Unless I am missing something, my opinion is that there is no reason to make the release. Perhaps if you just want to organize yourself, you can simply create a tag? I am not sure...

**Comment by papb** [comment]
Hello, after second thought, since performing these kind of releases is useful to you in other projects, then it means it's not useless. I think you can continue doing those, perhaps just adding a more descriptive release note, such as "minor changes to undocumented APIs" or something that helps consumers decide if they want to upgrade or not.

**Comment by ehmicky** [comment]
Yes you're right @papb, thanks for the kind feedback :)
