### ISSUE TITLE
Incorrect behaving?

### ISSUE THREAD

**Issue by tunnckoCore** [ehmicky/nve#12]
It probably can be fixed with #11.

**Describe the bug**

Not sure exactly if it's a bug. I'm trying to emulate that I'm using `nve` mainly (like after fresh system install), instead of NVM, to test what some paths will be.

**Steps to reproduce**

I'm on `node 12.13` through `nvm`. I installed, for example `pnpm`, globally through `nve 10 'npm i -g pnpm'` and expect to be able to run `pnpm` through that nve node 10, like `nve 10 'pnpm bin --global'`. Instead it says that the `pnpm` command is not found.

```
❯ nve --shell 10 'npm install --global pnpm'
/home/charlike/.cache/nve/bin/pnpm -> /home/charlike/.cache/nve/lib/node_modules/pnpm/bin/pnpm.js
/home/charlike/.cache/nve/bin/pnpx -> /home/charlike/.cache/nve/lib/node_modules/pnpm/bin/pnpx.js
+ pnpm@4.1.8
updated 1 package in 2.595s

❯ nve --shell 10 'pnpm bin --global'        
/bin/sh: pnpm: command not found

~/github/tunnckoCore/hela next*
❯ nve --shell 10 'npm bin --global' 
/home/charlike/.cache/nve/bin
(not in PATH env variable)
```

If I have `pnpm` installed normally (through nvm, eg. nvm's node/npm) it works, meaning it `nve --shell 10 'pnpm bin --global'` shows the nvm place of `pnpm` which is `/home/charlike/.nvm/versions/node/v12.13.0/bin`

**Expected behavior**

I expect what's installed through `nve` to be able to be called through `nve`, and exclusively.

Current behaving means that if i'm on a fresh machine and just use `nve` (and put in my shell) as my main daily driver instead of `nvm` it probably will show/do wrong things.

**Environment**

Enter the following command in a terminal and copy/paste its output:

```
Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
Yarn: 1.17.3 - ~/.nvm/versions/node/v12.13.0/bin/yarn
npm: 6.13.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
nve: 7.2.0
```

**Comment by ehmicky** [comment]
Hi @tunnckoCore, this is indeed the same problem as #11, so I will answer that issue instead. I will keep this issue open until #11 is done though.

**Comment by tunnckoCore** [comment]
Cool. Great! :)

> As a side note

Yea, I know.

**Comment by ehmicky** [comment]
@tunnckoCore this issue should be solved by the latest release [`7.3.0`](https://github.com/ehmicky/nve/releases/tag/7.3.0), could you please confirm it now works?

**Comment by tunnckoCore** [comment]
Yes, it's resolved..

**Comment by ehmicky** [comment]
Great! :tada:
