### ISSUE TITLE
npm lifecycle warning to use --scripts-prepend-node-path

### ISSUE THREAD

**Issue by papb** [ehmicky/nve#13]
Hello, first of all thanks for all the work on this :) <s>I have one silly question, sorry to open an issue</s>. This is my setup:

```js
// run.js
console.log('process.version', process.version);
```

```bash
$ nve 8 npm start
npm WARN lifecycle The node binary used for scripts is C:\Users\me\AppData\Local\nve\Cache\8.16.2\node.exe but npm is using C:\Program Files\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> testing_nve@1.0.0 start C:\Users\me\Desktop\testing_nve
> node run.js

process.version v8.16.2
```

What does the warning shown above by npm really mean?

```
npm WARN lifecycle The node binary used for scripts is C:\Users\me\AppData\Local\nve\Cache\8.16.2\node.exe but npm is using C:\Program Files\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

Thanks!

**Comment by ljharb** [comment]
It means your system node and nve node are different, and npm is using the system node instead of the nve node.

**Comment by ehmicky** [comment]
> I have one silly question, sorry to open an issue.

@papb There's no silly question! Please open as many silly issues as you wish :)

Which `npm --version` are you using? Does this happen if you use `npm@6.13.0`?

@ljharb, thanks for the help!

**Comment by ehmicky** [comment]
Update: this is not related to the `npm` version. This bug happens only on Windows. Investigating now.

**Comment by ehmicky** [comment]
Found the problem. 

`nve` relies on the `PATH` environment variable to ensure a specific `node` version is called. But on Windows, global binaries bypass that logic (I opened an issue at #14). However child processes triggered by that global binaries still use the `PATH` environment variable, so they use the correct Node.js version.

So when you do `nve 8 npm start` on Windows, `npm` is actually called with the system `node` (which is incorrect) and `run.js` is called with `node@8` (which is correct).

I am working on a solution to this problem.

**Comment by papb** [comment]
Oh, interesting, so it is actually a bug :open_mouth: 

Thanks!!

**Comment by ehmicky** [comment]
This bug should now be fixed in [`8.0.3`](https://github.com/ehmicky/nve/releases/tag/8.0.3). Please let me know if this works for you!

**Comment by ehmicky** [comment]
@all-contributors please add @papb for reporting this bug!

**Comment by ehmicky** [comment]
Alright, let's try again:
@all-contributors please add @papb for reporting this bug!
