### ISSUE TITLE
My console text turned green

### ISSUE THREAD

**Issue by papb** [ehmicky/nve#17]
**Describe the bug**

After using nve on windows' command prompt, my console text turned green:

![image](https://user-images.githubusercontent.com/20914054/77713036-21cb7600-6fb4-11ea-8326-c7b8aeb0799a.png)

**Steps to reproduce**

I am not sure if this is easy to reproduce, but as shown in the screenshot above I just ran `nve --arch=x32 12 node`.

**Expected behavior**

nve should not alter the text color :sweat_smile: 

**Environment**

* OS: Windows 7 6.1.7601
* Node: 12.14.1 - C:\NodeJS\node.EXE
* npm: 6.13.6 - C:\NodeJS\npm.CMD

**Can you submit a pull request?**

No... No time to investigate, sorry...

**Comment by ehmicky** [comment]
Thanks for reporting this issue!
 
I tried to reproduce it but could not.

![oh](https://user-images.githubusercontent.com/8136211/77754546-d18ffa80-702b-11ea-8cc5-f547b7f69aec.png)

I use the same commands in `cmd.exe`, with the same Node.js version. Some potential differences:
  - I used Windows 10, not Windows 7
  - I am using `nve@9.1.1`, which version are you using?

Can you reproduce the steps above, and does it give you the same result?

**Comment by papb** [comment]
Hello, thanks for the fast response, I am using nve@9.1.1 as well. I noticed the issue is caused by the download progress bar, which is green. If I open a new console and type the same command, nve will grab the node executable from cache and the text color is normal.

When you tried to reproduce, did you already have the executable in cache?

**Comment by ehmicky** [comment]
No I did not. Yes, it does look like this is related to the progress bar ([this line of code](https://github.com/ehmicky/fetch-node-website/blob/7973faaa19bc6d45c442ec18fee18fee40aff1ab/src/progress.js#L31)).

Do you manage to reproduce by trying over Node.js versions (which will show the progress bar)?

**Comment by papb** [comment]
Yes, happened again.

![image](https://user-images.githubusercontent.com/20914054/77813540-38430180-7088-11ea-8cad-7e3ef7a29339.png)

Then:

![image](https://user-images.githubusercontent.com/20914054/77813532-23ff0480-7088-11ea-9fb3-c456592ea6c5.png)

**Comment by ehmicky** [comment]
Thanks for checking.

I have removed the color on the progress bar, which should solve your problem. Can you please try [`nve@9.1.2`](https://github.com/ehmicky/nve/releases/tag/9.1.2) and confirm the problem is fixed?

**Comment by papb** [comment]
Yes it worked! Thank you very much!
