### ISSUE TITLE
Silent failure when 1-n Node.js versions don't have a binary for a given OS+architecture

### ISSUE THREAD

**Issue by ericcornelissen** [ehmicky/nve#36]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

The CLI will fail **without an error message** if at least one of multiple of the specified Node.js version don't have a binary available for the current platform. Example:

```sh
$ nve 10.13.0,12,14,16,18,19,20 some-command

  ⬢  Node.js 10.13.0  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  ⬢  Node.js 14.21.3  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

$ echo $?
1
```

### Steps to reproduce

1. Figure out your platform (OS + architecture)
2. Find a Node.js release that isn't available on your platform
3. Try to run `nve` with that release and at least one other release

### Configuration

- Command: `nve 10.13.0,12,14,16,18,19,20 some-command`
- No configuration file

### Environment

```
npx envinfo --system --binaries --browsers --npmPackages nve --npmGlobalPackages nve

  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 5.12 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.5
  npmPackages:
    nve: 16.0.0 => 16.0.0 
```

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @ericcornelissen,

Thanks for reporting this.
The problem seems to be that, after one of the downloads fails, the progress bars of the other downloads keep going. Therefore, the progress bar updates of the terminal overwrites the error message.
This should be fixed by adding a `signal` option to [`fetch-node-website`](https://github.com/ehmicky/fetch-node-website/blob/main/src/progress.js), so that `nve` can abort any ongoing download when it catches an exception.
Thanks for the issue.

**Comment by ericcornelissen** [comment]
> The problem seems to be that, after one of the downloads fails, the progress bars of the other downloads keep going. Therefore, the progress bar updates of the terminal overwrites the error message. This should be fixed by adding a `signal` option to [`fetch-node-website`](https://github.com/ehmicky/fetch-node-website/blob/main/src/progress.js),

That makes sense


> so that `nve` can abort any ongoing download when it catches an exception.

As a suggestion, I think it would make sense to provide the user with the ability to either ignore or not the ignore any failures due to missing platform binaries.


> You'll notice this by passing the `--no-progress` option, which prevents the bug from appearing then.
> 
> ```shell
> nve --no-progress 10.13.0,12,14,16,18,19,20 some-command
> ```

Verified this and you're correct.

**Comment by ehmicky** [comment]
@all-contributors Could you please add @ericcornelissen for bug?
