### ISSUE TITLE
Suggestions for "See also" section

### ISSUE THREAD

**Issue by balupton** [ehmicky/nve#44]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

I've been maintaining a similar tool https://github.com/bevry/testen since 2018, so maybe you'd find some of its dependencies and related projects useful:

- https://github.com/bevry/boundation uses testen to verify which editions of a project pass for which node.js versions, trimming unnecessary editions and failing if a required edition failed testing
- https://github.com/bevry/nodejs-versions api for fetching and filtering node.js versions
- https://github.com/bevry/nodejs-schedule
- https://github.com/bevry/nodejs-releases 
- https://github.com/bevry/nodejs-ecmascript-compatibility map nodejs versions and ecmascript versions
- https://github.com/bevry/ecmascript-versions
- https://github.com/bevry/version-clean 
- https://github.com/bevry/version-compare
- https://github.com/bevry/version-range how the above all compare ranges
- https://github.com/bevry/dorothy/blob/master/commands/nvm-env wraps nvm so that node.js versions that don't provide arm builds can still be installed on apple silicon, I'm thinking of baking this directly into testen or as its own npm package

### Describe the solution you'd like

Feel free to add whatever you think are useful to the see also section. I'll do the same for testen. I think there's enough room in the universe for both of them.

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @balupton,

Thanks, that's very interesting! There is definitely lots of related logic there.

I would prefer leaving this list in this issue, and keep the one in the `README` only for the ecosystem of `nve` itself.
But thanks a lot for sharing!

**Comment by balupton** [comment]
No worries.

Reach out anytime if you want help incorporating any of its functionality into nve.
