### ISSUE TITLE
Adding of more flags in the CLI

### ISSUE THREAD

**Issue by Hongarc** [ehmicky/nve#8]
Current version just support version range.

How about adding `--version`, `--help`, .etc?

Thank you.

**Comment by ehmicky** [comment]
`nve {version} ...` simply forwards to `node ...`. `nve` does not have any CLI flags on its own.

Adding `--version` or `--help` would break this. I would prefer to keep `nve` simple and simply forwarding to `node`. Future features are probably going to be implemented as environment variables or though a configuration file.

**Comment by ehmicky** [comment]
The latest major release [`3.0.0`](https://github.com/ehmicky/nve/releases/tag/3.0.0) has added the `--version` and `--help` flags.
